import boundary_values_solutions_elliptic_equations_theorem_canonical_lane_mathlib.GateLemmas
namespace HautevilleHouse
namespace boundary_values_solutions_elliptic_equations_theorem_canonical_lane_mathlib
structure ConstrainedTheoremClosure where
  admissible :: intro :: constraint :: consequence :: proof ::
theorem canonical : ConstrainedTheoremClosure :=
  ConstrainedTheoremClosure.intro
end boundary_values_solutions_elliptic_equations_theorem_canonical_lane_mathlib
end HautevilleHouse
